fos_rest:
    view:
        formats:
            json: true
    format_listener:
        rules:
            - { path: ^/, prefer_extension: true, fallback_format: json, priorities: [ json ] }
    body_converter:
        enabled: true
        validate: true
        validation_errors_argument: validationErrors
